// Generated by qwen_tb_generator.py. Multi-layer stream wrapper scaffold.
module QwenLayerPipelineTop #(
  parameter integer NUM_LAYERS = 24,
  parameter integer DATA_W = 256,
  parameter integer ADDR_W = 11,
  parameter integer CFG_SEQ_W = 5,
  parameter integer POS_W = 4
) (
  input                  clock,
  input                  reset,
  input                  io_start,
  input  [CFG_SEQ_W-1:0] io_cfg_seqlen,
  input                  io_cfg_prefill,
  input                  io_cfg_singleQuery,
  input                  io_cfgValid,
  input  [POS_W-1:0]     io_position,
  output                 io_in_ready,
  input                  io_in_valid,
  input  [DATA_W-1:0]    io_in_bits_data,
  input                  io_in_bits_st,
  input  [ADDR_W-1:0]    io_in_bits_addr,
  input                  io_in_bits_last,
  input                  io_out_ready,
  output                 io_out_valid,
  output [DATA_W-1:0]    io_out_bits_data,
  output                 io_out_bits_st,
  output [ADDR_W-1:0]    io_out_bits_addr,
  output                 io_out_bits_last
);
  wire [NUM_LAYERS:0] valid;
  wire [NUM_LAYERS:0] ready;
  wire [NUM_LAYERS:0] st;
  wire [NUM_LAYERS:0] last;
  wire [DATA_W-1:0] data [0:NUM_LAYERS];
  wire [ADDR_W-1:0] addr [0:NUM_LAYERS];

  assign valid[0] = io_in_valid;
  assign data[0] = io_in_bits_data;
  assign st[0] = io_in_bits_st;
  assign addr[0] = io_in_bits_addr;
  assign last[0] = io_in_bits_last;
  assign io_in_ready = ready[0];

  assign ready[NUM_LAYERS] = io_out_ready;
  assign io_out_valid = valid[NUM_LAYERS];
  assign io_out_bits_data = data[NUM_LAYERS];
  assign io_out_bits_st = st[NUM_LAYERS];
  assign io_out_bits_addr = addr[NUM_LAYERS];
  assign io_out_bits_last = last[NUM_LAYERS];
  wire unused_cfg = |{io_cfg_seqlen, io_cfg_prefill, io_cfg_singleQuery, io_cfgValid};

  genvar i;
  generate
    for (i = 0; i < NUM_LAYERS; i = i + 1) begin : g_layer
      GeneratedAcceleratorTop layer (
        .clock(clock),
        .reset(reset),
        .io_start(io_start),
        .io_position(io_position),
        .io_in_ready(ready[i]),
        .io_in_valid(valid[i]),
        .io_in_bits_data(data[i]),
        .io_in_bits_st(st[i]),
        .io_in_bits_addr(addr[i]),
        .io_in_bits_last(last[i]),
        .io_out_ready(ready[i + 1]),
        .io_out_valid(valid[i + 1]),
        .io_out_bits_data(data[i + 1]),
        .io_out_bits_st(st[i + 1]),
        .io_out_bits_addr(addr[i + 1]),
        .io_out_bits_last(last[i + 1])
      );
    end
  endgenerate
endmodule

module QwenMultiLayerSystemTop #(
  parameter integer NUM_LAYERS = 24,
  parameter integer DATA_W = 256,
  parameter integer ADDR_W = 11,
  parameter integer CFG_SEQ_W = 5,
  parameter integer POS_W = 4
) (
  input                  clock,
  input                  reset,
  input                  io_start,
  input  [CFG_SEQ_W-1:0] io_cfg_seqlen,
  input                  io_cfg_prefill,
  input                  io_cfg_singleQuery,
  input                  io_cfgValid,
  input  [POS_W-1:0]     io_position,
  output                 io_in_ready,
  input                  io_in_valid,
  input  [DATA_W-1:0]    io_in_bits_data,
  input                  io_in_bits_st,
  input  [ADDR_W-1:0]    io_in_bits_addr,
  input                  io_in_bits_last,
  input                  io_out_ready,
  output                 io_out_valid,
  output [DATA_W-1:0]    io_out_bits_data,
  output                 io_out_bits_st,
  output [ADDR_W-1:0]    io_out_bits_addr,
  output                 io_out_bits_last
);
  QwenLayerPipelineTop #(
    .NUM_LAYERS(NUM_LAYERS),
    .DATA_W(DATA_W),
    .ADDR_W(ADDR_W),
    .CFG_SEQ_W(CFG_SEQ_W),
    .POS_W(POS_W)
  ) pipeline (
    .clock(clock),
    .reset(reset),
    .io_start(io_start),
    .io_cfg_seqlen(io_cfg_seqlen),
    .io_cfg_prefill(io_cfg_prefill),
    .io_cfg_singleQuery(io_cfg_singleQuery),
    .io_cfgValid(io_cfgValid),
    .io_position(io_position),
    .io_in_ready(io_in_ready),
    .io_in_valid(io_in_valid),
    .io_in_bits_data(io_in_bits_data),
    .io_in_bits_st(io_in_bits_st),
    .io_in_bits_addr(io_in_bits_addr),
    .io_in_bits_last(io_in_bits_last),
    .io_out_ready(io_out_ready),
    .io_out_valid(io_out_valid),
    .io_out_bits_data(io_out_bits_data),
    .io_out_bits_st(io_out_bits_st),
    .io_out_bits_addr(io_out_bits_addr),
    .io_out_bits_last(io_out_bits_last)
  );
endmodule
