// Generated by qwen_tb_generator.py. Qwen AXI/DDR wrapper scaffold.
module QwenAxiBoardSystemTop #(
  parameter integer NUM_LAYERS = 24,
  parameter integer DATA_W = 256,
  parameter integer ADDR_W = 11,
  parameter integer CFG_SEQ_W = 5,
  parameter integer POS_W = 4,
  parameter integer HIDDEN_SIZE = 896,
  parameter integer LANES = 8,
  parameter integer STREAM_BEATS = 1792,
  parameter integer WEIGHT_PREFETCH_BEATS = 32,
  parameter integer AXI_DATA_W = 256,
  parameter integer AXI_STRB_W = AXI_DATA_W / 8
) (
  input                    clock,
  input                    reset,
  input                    io_start,
  input  [15:0]            io_cfg_seqlen,
  input                    io_cfg_prefill,
  input                    io_cfg_single_query,
  input  [63:0]            io_input_base_addr,
  input  [63:0]            io_weight_base_addr,
  input  [63:0]            io_output_base_addr,
  input  [31:0]            io_output_stride_bytes,
  output reg [5:0]         io_m_axi_awid,
  output reg [63:0]        io_m_axi_awaddr,
  output reg [7:0]         io_m_axi_awlen,
  output reg [2:0]         io_m_axi_awsize,
  output reg [1:0]         io_m_axi_awburst,
  output reg [0:0]         io_m_axi_awlock,
  output reg [3:0]         io_m_axi_awcache,
  output reg [2:0]         io_m_axi_awprot,
  output reg [3:0]         io_m_axi_awregion,
  output reg [3:0]         io_m_axi_awqos,
  output reg               io_m_axi_awvalid,
  input                    io_m_axi_awready,
  output reg [AXI_DATA_W-1:0] io_m_axi_wdata,
  output reg [AXI_STRB_W-1:0] io_m_axi_wstrb,
  output reg               io_m_axi_wlast,
  output reg               io_m_axi_wvalid,
  input                    io_m_axi_wready,
  input      [5:0]         io_m_axi_bid,
  input      [1:0]         io_m_axi_bresp,
  input                    io_m_axi_bvalid,
  output reg               io_m_axi_bready,
  output reg [5:0]         io_m_axi_arid,
  output reg [63:0]        io_m_axi_araddr,
  output reg [7:0]         io_m_axi_arlen,
  output reg [2:0]         io_m_axi_arsize,
  output reg [1:0]         io_m_axi_arburst,
  output reg [0:0]         io_m_axi_arlock,
  output reg [3:0]         io_m_axi_arcache,
  output reg [2:0]         io_m_axi_arprot,
  output reg [3:0]         io_m_axi_arregion,
  output reg [3:0]         io_m_axi_arqos,
  output reg               io_m_axi_arvalid,
  input                    io_m_axi_arready,
  input      [5:0]         io_m_axi_rid,
  input      [AXI_DATA_W-1:0] io_m_axi_rdata,
  input      [1:0]         io_m_axi_rresp,
  input                    io_m_axi_rlast,
  input                    io_m_axi_rvalid,
  output reg               io_m_axi_rready,
  output reg [DATA_W-1:0]  io_res,
  output reg               io_res_st,
  output reg [31:0]        io_res_addr,
  output reg               io_res_valid,
  output reg               io_res_last,
  output                   io_done,
  output reg               io_error
);
  localparam [2:0]
    RD_IDLE       = 3'd0,
    RD_WEIGHT_AR  = 3'd1,
    RD_WEIGHT     = 3'd2,
    RD_INPUT_AR   = 3'd3,
    RD_INPUT      = 3'd4,
    RD_FLUSH      = 3'd5,
    RD_DONE       = 3'd6;
  localparam [1:0]
    WR_IDLE       = 2'd0,
    WR_AW         = 2'd1,
    WR_W          = 2'd2,
    WR_B          = 2'd3;

  reg [2:0] rd_state;
  reg [1:0] wr_state;
  reg [15:0] read_idx;
  reg [15:0] weight_idx;
  reg [15:0] stream_beats;
  reg [15:0] weight_beats;
  reg [31:0] write_idx;
  reg [31:0] output_count;
  reg [DATA_W-1:0] write_data;
  reg write_st;
  reg write_last;
  reg [ADDR_W-1:0] write_addr;
  reg [DATA_W-1:0] weight_mix;
  reg seen_output;
  reg seen_output_last;
  localparam integer TOKEN_BEATS = HIDDEN_SIZE / LANES;
  wire reading_weight = rd_state == RD_WEIGHT;
  wire reading_input = rd_state == RD_INPUT;
  wire [15:0] token_beat_idx = read_idx % TOKEN_BEATS;
  wire [15:0] input_remaining = stream_beats - read_idx;
  wire [15:0] weight_remaining = weight_beats - weight_idx;
  wire [8:0] input_burst_beats = (input_remaining > 16'd256) ? 9'd256 : {1'b0, input_remaining[7:0]};
  wire [8:0] weight_burst_beats = (weight_remaining > 16'd256) ? 9'd256 : {1'b0, weight_remaining[7:0]};
  wire [8:0] ar_burst_beats = (rd_state == RD_WEIGHT_AR) ? weight_burst_beats : input_burst_beats;
  wire [DATA_W-1:0] core_in_data = io_m_axi_rdata[DATA_W-1:0] ^ weight_mix;

  wire core_in_valid = reading_input && io_m_axi_rvalid;
  wire core_in_ready;
  wire core_out_valid;
  wire core_out_ready = wr_state == WR_IDLE;
  wire [DATA_W-1:0] core_out_data;
  wire core_out_st;
  wire [ADDR_W-1:0] core_out_addr;
  wire core_out_last;
  wire [CFG_SEQ_W-1:0] core_cfg_seqlen = io_cfg_seqlen[CFG_SEQ_W-1:0];

  assign io_done = (rd_state == RD_DONE) && (output_count >= {16'd0, stream_beats}) && (wr_state == WR_IDLE);

  QwenMultiLayerSystemTop #(
    .NUM_LAYERS(NUM_LAYERS),
    .DATA_W(DATA_W),
    .ADDR_W(ADDR_W),
    .CFG_SEQ_W(CFG_SEQ_W),
    .POS_W(POS_W)
  ) core (
    .clock(clock),
    .reset(reset),
    .io_start(io_start),
    .io_cfg_seqlen(core_cfg_seqlen),
    .io_cfg_prefill(io_cfg_prefill),
    .io_cfg_singleQuery(io_cfg_single_query),
    .io_cfgValid(io_start),
    .io_position(4'd0),
    .io_in_ready(core_in_ready),
    .io_in_valid(core_in_valid),
    .io_in_bits_data(core_in_data),
    .io_in_bits_st(token_beat_idx == 16'd0),
    .io_in_bits_addr(token_beat_idx[ADDR_W-1:0]),
    .io_in_bits_last(token_beat_idx == (TOKEN_BEATS - 1)),
    .io_out_ready(core_out_ready),
    .io_out_valid(core_out_valid),
    .io_out_bits_data(core_out_data),
    .io_out_bits_st(core_out_st),
    .io_out_bits_addr(core_out_addr),
    .io_out_bits_last(core_out_last)
  );

  always @(*) begin
    io_m_axi_awid = 6'd0;
    io_m_axi_awaddr = io_output_base_addr + (write_idx * io_output_stride_bytes);
    io_m_axi_awlen = 8'd0;
    io_m_axi_awsize = 3'd5;
    io_m_axi_awburst = 2'b01;
    io_m_axi_awlock = 1'b0;
    io_m_axi_awcache = 4'b0011;
    io_m_axi_awprot = 3'b000;
    io_m_axi_awregion = 4'd0;
    io_m_axi_awqos = 4'd0;
    io_m_axi_awvalid = (wr_state == WR_AW);
    io_m_axi_wdata = write_data;
    io_m_axi_wstrb = '1;
    io_m_axi_wlast = 1'b1;
    io_m_axi_wvalid = (wr_state == WR_W);
    io_m_axi_bready = (wr_state == WR_B);
    io_m_axi_arid = 6'd0;
    io_m_axi_araddr = (rd_state == RD_WEIGHT_AR)
      ? io_weight_base_addr + (weight_idx * (AXI_DATA_W / 8))
      : io_input_base_addr + (read_idx * (AXI_DATA_W / 8));
    io_m_axi_arlen = ar_burst_beats[7:0] - 8'd1;
    io_m_axi_arsize = 3'd5;
    io_m_axi_arburst = 2'b01;
    io_m_axi_arlock = 1'b0;
    io_m_axi_arcache = 4'b0011;
    io_m_axi_arprot = 3'b000;
    io_m_axi_arregion = 4'd0;
    io_m_axi_arqos = 4'd0;
    io_m_axi_arvalid = (rd_state == RD_WEIGHT_AR) || (rd_state == RD_INPUT_AR);
    io_m_axi_rready = reading_weight || (reading_input && core_in_ready);
  end

  always @(posedge clock) begin
    if (reset) begin
      rd_state <= RD_IDLE;
      wr_state <= WR_IDLE;
      read_idx <= 16'd0;
      weight_idx <= 16'd0;
      stream_beats <= 16'd1;
      weight_beats <= 16'd1;
      write_idx <= 32'd0;
      output_count <= 32'd0;
      write_data <= '0;
      write_st <= 1'b0;
      write_last <= 1'b0;
      write_addr <= '0;
      weight_mix <= '0;
      seen_output <= 1'b0;
      seen_output_last <= 1'b0;
      io_res <= '0;
      io_res_st <= 1'b0;
      io_res_addr <= 32'd0;
      io_res_valid <= 1'b0;
      io_res_last <= 1'b0;
      io_error <= 1'b0;
    end else begin
      io_res_valid <= 1'b0;
      if (core_out_valid && core_out_ready) begin
        write_data <= core_out_data;
        write_st <= core_out_st;
        write_last <= core_out_last;
        write_addr <= core_out_addr;
        io_res <= core_out_data;
        io_res_st <= core_out_st;
        io_res_addr <= {21'd0, core_out_addr};
        io_res_valid <= 1'b1;
        io_res_last <= core_out_last;
        seen_output <= 1'b1;
        seen_output_last <= seen_output_last | core_out_last;
        wr_state <= WR_AW;
      end else begin
        case (wr_state)
          WR_IDLE: begin
            wr_state <= WR_IDLE;
          end
          WR_AW: begin
            if (io_m_axi_awvalid && io_m_axi_awready) wr_state <= WR_W;
          end
          WR_W: begin
            if (io_m_axi_wvalid && io_m_axi_wready) wr_state <= WR_B;
          end
          WR_B: begin
            if (io_m_axi_bvalid && io_m_axi_bready) begin
              if (io_m_axi_bresp != 2'b00) io_error <= 1'b1;
              write_idx <= write_idx + 32'd1;
              output_count <= output_count + 32'd1;
              wr_state <= WR_IDLE;
            end
          end
          default: wr_state <= WR_IDLE;
        endcase
      end

      case (rd_state)
        RD_IDLE: begin
          if (io_start) begin
            stream_beats <= STREAM_BEATS[15:0];
            weight_beats <= WEIGHT_PREFETCH_BEATS[15:0];
            read_idx <= 16'd0;
            weight_idx <= 16'd0;
            write_idx <= 32'd0;
            output_count <= 32'd0;
            weight_mix <= '0;
            seen_output <= 1'b0;
            seen_output_last <= 1'b0;
            io_error <= 1'b0;
            rd_state <= (WEIGHT_PREFETCH_BEATS == 0) ? RD_INPUT_AR : RD_WEIGHT_AR;
          end
        end
        RD_WEIGHT_AR: begin
          if (io_m_axi_arvalid && io_m_axi_arready) rd_state <= RD_WEIGHT;
        end
        RD_WEIGHT: begin
          if (io_m_axi_rvalid && io_m_axi_rready) begin
            if (io_m_axi_rresp != 2'b00) io_error <= 1'b1;
            weight_mix <= {weight_mix[DATA_W-2:0], weight_mix[DATA_W-1]} ^ io_m_axi_rdata[DATA_W-1:0] ^ {240'd0, weight_idx};
            weight_idx <= weight_idx + 16'd1;
            if (io_m_axi_rlast || weight_idx == (weight_beats - 16'd1)) begin
              rd_state <= (weight_idx == (weight_beats - 16'd1)) ? RD_INPUT_AR : RD_WEIGHT_AR;
            end
          end
        end
        RD_INPUT_AR: begin
          if (io_m_axi_arvalid && io_m_axi_arready) rd_state <= RD_INPUT;
        end
        RD_INPUT: begin
          if (io_m_axi_rvalid && io_m_axi_rready) begin
            if (io_m_axi_rresp != 2'b00) io_error <= 1'b1;
            read_idx <= read_idx + 16'd1;
            if (io_m_axi_rlast || read_idx == (stream_beats - 16'd1)) begin
              rd_state <= (read_idx == (stream_beats - 16'd1)) ? RD_FLUSH : RD_INPUT_AR;
            end
          end
        end
        RD_FLUSH: begin
          if (output_count >= {16'd0, stream_beats} && wr_state == WR_IDLE) rd_state <= RD_DONE;
        end
        RD_DONE: begin
          rd_state <= RD_DONE;
        end
        default: rd_state <= RD_IDLE;
      endcase
    end
  end
endmodule
