#!/usr/bin/env python3
"""Inspect and drive an existing app-shell Vivado project for runtime integration.

This tool is intentionally contract-driven. The framework core supplies a
generic app-shell integration contract; board/model-specific details must come
from that contract or from the user-provided tool environment.
"""

from __future__ import annotations

import argparse
import json
import os
import shlex
import shutil
import subprocess
import sys
import time
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from accagent.framework.semantic_simulator import persistent_remote_tool_workdir


def read_json(path: Path) -> dict[str, Any]:
    with path.open("r", encoding="utf-8") as f:
        data = json.load(f)
    if not isinstance(data, dict):
        raise ValueError(f"expected JSON object: {path}")
    return data


def write_json(path: Path, data: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, sort_keys=True)
        f.write("\n")


def nonblank(value: Any) -> bool:
    return value is not None and value != "" and value != [] and str(value).strip().lower() not in {"none", "null"}


def first_nonblank(*values: Any) -> Any:
    for value in values:
        if nonblank(value):
            return value
    return None


def tcl_quote(value: Any) -> str:
    text = str(value or "")
    return "{" + text.replace("\\", "\\\\").replace("}", "\\}") + "}"


def check_file(path: Path, label: str) -> tuple[bool, dict[str, Any]]:
    exists = path.exists()
    size = path.stat().st_size if exists else 0
    return exists and size > 0, {"name": label, "status": "pass" if exists and size > 0 else "fail", "path": str(path), "size_bytes": size}


def run_cmd(argv: list[str], timeout_sec: int | None = None) -> dict[str, Any]:
    started = time.monotonic()
    try:
        proc = subprocess.run(argv, text=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=timeout_sec, check=False)
        return {
            "argv": argv,
            "returncode": proc.returncode,
            "stdout_tail": proc.stdout[-8000:],
            "stderr_tail": proc.stderr[-8000:],
            "duration_sec": time.monotonic() - started,
        }
    except subprocess.TimeoutExpired as exc:
        return {
            "argv": argv,
            "returncode": 124,
            "stdout_tail": (exc.stdout or "")[-8000:] if isinstance(exc.stdout, str) else "",
            "stderr_tail": (exc.stderr or "")[-8000:] if isinstance(exc.stderr, str) else "",
            "duration_sec": time.monotonic() - started,
        }


def parse_kv_report(path: Path) -> dict[str, str]:
    result: dict[str, str] = {}
    if not path.exists():
        return result
    for line in path.read_text(encoding="utf-8", errors="ignore").splitlines():
        if "=" not in line:
            continue
        key, value = line.split("=", 1)
        result[key.strip()] = value.strip()
    return result


def split_report_list(value: str, limit: int = 80) -> list[str]:
    if not value:
        return []
    return [item for item in (part.strip() for part in value.split(",")) if item][:limit]


def build_tcl(project_xpr: str, signal_prefix: str, target_ip_name: str, mode: str) -> str:
    return f"""# Generated by SpatialAccAgent app_shell_runtime_vivado.py.
set project_xpr {tcl_quote(project_xpr)}
set signal_prefix {tcl_quote(signal_prefix)}
set target_ip_name {tcl_quote(target_ip_name)}
set mode {tcl_quote(mode)}
set report_path "app_shell_runtime_inspection.txt"

proc record {{fh key value}} {{
  set clean [string map [list "\\n" " " "\\r" " " "=" ":"] $value]
  puts $fh "$key=$clean"
  puts "SPATIALACC_APP_SHELL $key=$clean"
}}

set fh [open $report_path w]
record $fh project_xpr $project_xpr
record $fh signal_prefix $signal_prefix
record $fh target_ip_name $target_ip_name
record $fh mode $mode

if {{![file exists $project_xpr]}} {{
  record $fh project_exists 0
  close $fh
  exit 0
}}
record $fh project_exists 1

set open_status [catch {{open_project $project_xpr}} open_message]
record $fh open_project_status $open_status
record $fh open_project_message $open_message
if {{$open_status != 0}} {{
  close $fh
  exit 0
}}

set project_dir [file dirname $project_xpr]
record $fh project_dir $project_dir
record $fh current_project [current_project]
record $fh top_file_set [current_fileset]
record $fh fileset_top [get_property TOP [current_fileset]]

set runs [get_runs]
record $fh runs [join $runs ","]
foreach run $runs {{
  record $fh "run_status.$run" [get_property STATUS $run]
  record $fh "run_directory.$run" [get_property DIRECTORY $run]
}}

set bd_files [get_files -quiet *.bd]
record $fh bd_files [join $bd_files ","]
record $fh bd_count [llength $bd_files]
set total_prefix_pins 0
set total_prefix_cells 0
set total_intf_pins 0
set total_axi_intf_pins 0
set intf_pin_samples {{}}
set axi_intf_pin_samples {{}}
set cell_samples {{}}
set axi_candidate_cell_samples {{}}
set target_matches {{}}
foreach bd $bd_files {{
  set bd_status [catch {{open_bd_design $bd}} bd_message]
  record $fh "bd_open_status.$bd" $bd_status
  record $fh "bd_open_message.$bd" $bd_message
  if {{$bd_status != 0}} {{
    continue
  }}
  set cells [get_bd_cells -quiet -hier *]
  set pins [get_bd_pins -quiet -hier *$signal_prefix*]
  set nets [get_bd_nets -quiet -hier *$signal_prefix*]
  record $fh "bd_cells_count.$bd" [llength $cells]
  record $fh "bd_prefix_pins_count.$bd" [llength $pins]
  record $fh "bd_prefix_nets_count.$bd" [llength $nets]
  if {{[llength $pins] > 0}} {{
    record $fh "bd_prefix_pins.$bd" [join [lrange $pins 0 40] ","]
  }}
  incr total_prefix_pins [llength $pins]
  set prefix_cells [get_bd_cells -quiet -hier *$signal_prefix*]
  incr total_prefix_cells [llength $prefix_cells]
  set intf_pins [get_bd_intf_pins -quiet -hier *]
  foreach pin $intf_pins {{
    if {{[llength $intf_pin_samples] < 160}} {{
      lappend intf_pin_samples $pin
    }}
  }}
  incr total_intf_pins [llength $intf_pins]
  set axi_intf_pins {{}}
  foreach pin $intf_pins {{
    set lower_pin [string tolower $pin]
    if {{[string match "*axi*" $lower_pin] || [string match "*ddr*" $lower_pin]}} {{
      lappend axi_intf_pins $pin
      if {{[llength $axi_intf_pin_samples] < 120}} {{
        lappend axi_intf_pin_samples $pin
      }}
    }}
  }}
  record $fh "bd_intf_pins_count.$bd" [llength $intf_pins]
  if {{[llength $intf_pins] > 0}} {{
    record $fh "bd_intf_pins.$bd" [join [lrange $intf_pins 0 80] ","]
  }}
  record $fh "bd_axi_intf_pins_count.$bd" [llength $axi_intf_pins]
  if {{[llength $axi_intf_pins] > 0}} {{
    record $fh "bd_axi_intf_pins.$bd" [join [lrange $axi_intf_pins 0 80] ","]
  }}
  incr total_axi_intf_pins [llength $axi_intf_pins]
  set axi_candidate_cells {{}}
  foreach cell $cells {{
    set vlnv [get_property -quiet VLNV $cell]
    if {{[llength $cell_samples] < 160}} {{
      lappend cell_samples "$cell|$vlnv"
    }}
    set lower_cell [string tolower "$cell $vlnv"]
    if {{[string match "*axi*" $lower_cell] || [string match "*ddr*" $lower_cell] || [string match "*xdma*" $lower_cell] || [string match "*interconnect*" $lower_cell] || [string match "*smartconnect*" $lower_cell]}} {{
      lappend axi_candidate_cells "$cell|$vlnv"
      if {{[llength $axi_candidate_cell_samples] < 120}} {{
        lappend axi_candidate_cell_samples "$cell|$vlnv"
      }}
    }}
  }}
  record $fh "bd_axi_candidate_cells_count.$bd" [llength $axi_candidate_cells]
  if {{[llength $axi_candidate_cells] > 0}} {{
    record $fh "bd_axi_candidate_cells.$bd" [join [lrange $axi_candidate_cells 0 80] ","]
  }}
  if {{$target_ip_name ne ""}} {{
    set matches [get_bd_cells -quiet -hier *$target_ip_name*]
    set target_matches [concat $target_matches $matches]
  }}
}}
record $fh total_prefix_pins $total_prefix_pins
record $fh total_prefix_cells $total_prefix_cells
record $fh total_intf_pins $total_intf_pins
record $fh total_axi_intf_pins $total_axi_intf_pins
record $fh intf_pin_samples [join $intf_pin_samples ","]
record $fh axi_intf_pin_samples [join $axi_intf_pin_samples ","]
record $fh cell_samples [join $cell_samples ","]
record $fh axi_candidate_cell_samples [join $axi_candidate_cell_samples ","]
record $fh target_match_count [llength $target_matches]
if {{[llength $target_matches] > 0}} {{
  record $fh target_matches [join $target_matches ","]
}}

set project_files [get_files -quiet *]
set sv_count 0
foreach f $project_files {{
  if {{[string match "*.sv" $f] || [string match "*.v" $f]}} {{
    incr sv_count
  }}
}}
record $fh project_hdl_file_count $sv_count

if {{$target_ip_name eq ""}} {{
  record $fh integration_ready 0
  record $fh integration_blocker "no integration target IP/block declared in app-shell contract or SPATIALACC_APP_SHELL_TARGET_IP"
}} elseif {{[llength $target_matches] == 0}} {{
  record $fh integration_ready 0
  record $fh integration_blocker "declared integration target was not found in the open app-shell block design"
}} elseif {{$mode ne "bitstream"}} {{
  record $fh integration_ready 1
  record $fh integration_blocker "inspection mode only; bitstream was not requested"
}} else {{
  record $fh integration_ready 0
  record $fh integration_blocker "target found, but generic RTL replacement/BD rewiring adapter is not implemented for this shell contract"
}}

close_project
close $fh
exit 0
"""


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Run app-shell runtime Vivado integration evidence.")
    parser.add_argument("--run-dir", type=Path, required=True)
    parser.add_argument("--contract", type=Path, required=True)
    parser.add_argument("--wrapper-rtl", type=Path, required=True)
    parser.add_argument("--mode", choices=["inspect", "bitstream"], default="bitstream")
    parser.add_argument("--out", type=Path, required=True)
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(sys.argv[1:] if argv is None else argv)
    run_dir = args.run_dir.resolve()
    contract = read_json(args.contract) if args.contract.exists() else {}
    shell = contract.get("shell_project", {}) if isinstance(contract.get("shell_project"), dict) else {}
    board = contract.get("board_interface", {}) if isinstance(contract.get("board_interface"), dict) else {}
    integration = contract.get("integration_target", {}) if isinstance(contract.get("integration_target"), dict) else {}
    target_discovery = contract.get("target_discovery", {}) if isinstance(contract.get("target_discovery"), dict) else {}
    runtime_abi = contract.get("runtime_abi", {}) if isinstance(contract.get("runtime_abi"), dict) else {}

    remote_host = first_nonblank(os.environ.get("REMOTE_HOST"), shell.get("remote_host"), runtime_abi.get("remote_host"))
    remote_port = str(first_nonblank(os.environ.get("REMOTE_PORT"), shell.get("remote_ssh_port"), "22"))
    vivado_bin = str(first_nonblank(os.environ.get("VIVADO_BIN"), ""))
    remote_known_hosts = os.environ.get("REMOTE_KNOWN_HOSTS", "/tmp/codex_ssh_known_hosts").strip()
    remote_workdir = os.environ.get(
        "REMOTE_WORKDIR",
        persistent_remote_tool_workdir(
            str(remote_host or ""), "vivado_app_shell_runtime", run_dir.name
        ),
    ).strip()
    project_xpr = str(first_nonblank(os.environ.get("SPATIALACC_APP_SHELL_PROJECT_XPR"), shell.get("vivado_project_path"), ""))
    signal_prefix = str(first_nonblank(board.get("signal_prefix"), "") or "")
    target_ip_name = str(first_nonblank(os.environ.get("SPATIALACC_APP_SHELL_TARGET_IP"), integration.get("ip_name"), integration.get("bd_cell"), "") or "")

    out_dir = run_dir / "app_shell_runtime_bitstream"
    scripts_dir = run_dir / "generated" / "backend" / "scripts"
    tcl_path = scripts_dir / "app_shell_runtime_vivado.tcl"
    inspection_path = out_dir / "app_shell_runtime_inspection.txt"

    checks: list[dict[str, Any]] = []
    blockers: list[str] = []
    for label, path in [("contract", args.contract), ("wrapper_rtl", args.wrapper_rtl)]:
        ok, item = check_file(path, label)
        checks.append(item)
        if not ok:
            blockers.append(f"missing or empty {label}: {path}")
    for name, value in [
        ("shell_project.vivado_project_path", project_xpr),
        ("board_interface.signal_prefix", signal_prefix),
        ("REMOTE_HOST", remote_host),
        ("VIVADO_BIN", vivado_bin),
    ]:
        if not nonblank(value):
            blockers.append(f"{name} is not configured")

    commands: list[dict[str, Any]] = []
    inspection: dict[str, str] = {}
    if not blockers:
        tcl_path.parent.mkdir(parents=True, exist_ok=True)
        tcl_path.write_text(build_tcl(project_xpr, signal_prefix, target_ip_name, args.mode), encoding="utf-8")
        ssh_base = [
            "ssh",
            "-o",
            "StrictHostKeyChecking=no",
            "-o",
            f"UserKnownHostsFile={remote_known_hosts}",
            "-p",
            remote_port,
            str(remote_host),
        ]
        scp_base = [
            "scp",
            "-q",
            "-P",
            remote_port,
            "-o",
            "StrictHostKeyChecking=no",
            "-o",
            f"UserKnownHostsFile={remote_known_hosts}",
        ]
        commands.append(run_cmd([*ssh_base, f"mkdir -p {shlex.quote(remote_workdir)} && rm -f {shlex.quote(remote_workdir)}/*"], 120))
        commands.append(run_cmd([*scp_base, str(tcl_path), str(args.contract), str(args.wrapper_rtl), f"{remote_host}:{remote_workdir}/"], 300))
        stamp = time.strftime("%Y%m%d_%H%M%S")
        remote_vivado = (
            f"cd {shlex.quote(remote_workdir)} && "
            f"{shlex.quote(str(vivado_bin))} -mode batch -source app_shell_runtime_vivado.tcl "
            f"-log app_shell_runtime_{stamp}.log -journal app_shell_runtime.jou"
        )
        commands.append(run_cmd([*ssh_base, remote_vivado], None))
        out_dir.mkdir(parents=True, exist_ok=True)
        commands.append(run_cmd([*scp_base, f"{remote_host}:{remote_workdir}/app_shell_runtime_inspection.txt", str(inspection_path)], 300))
        commands.append(run_cmd([*scp_base, f"{remote_host}:{remote_workdir}/app_shell_runtime_*.log", str(out_dir) + "/"], 300))
        for command in commands:
            if command.get("returncode") != 0:
                blockers.append(f"command failed returncode={command.get('returncode')}: {' '.join(command.get('argv', [])[:3])}")
                break
        inspection = parse_kv_report(inspection_path)

    if inspection:
        total_prefix_pins = int(inspection.get("total_prefix_pins", "0") or 0)
        total_intf_pins = int(inspection.get("total_intf_pins", "0") or 0)
        total_axi_intf_pins = int(inspection.get("total_axi_intf_pins", "0") or 0)
        intf_pin_samples = split_report_list(inspection.get("intf_pin_samples", ""))
        axi_intf_pin_samples = split_report_list(inspection.get("axi_intf_pin_samples", ""))
        cell_samples = split_report_list(inspection.get("cell_samples", ""))
        axi_candidate_cell_samples = split_report_list(inspection.get("axi_candidate_cell_samples", ""))
        bd_open_failures = [
            {"bd": key.removeprefix("bd_open_status."), "message": inspection.get(f"bd_open_message.{key.removeprefix('bd_open_status.')}", "")}
            for key, value in inspection.items()
            if key.startswith("bd_open_status.") and value != "0"
        ]
        checks.append({"name": "app_shell_project_exists", "status": "pass" if inspection.get("project_exists") == "1" else "fail", "summary": f"project_xpr={project_xpr}"})
        checks.append({"name": "app_shell_project_opened", "status": "pass" if inspection.get("open_project_status") == "0" else "fail", "summary": inspection.get("open_project_message", "")})
        checks.append({"name": "app_shell_bd_present", "status": "pass" if int(inspection.get("bd_count", "0") or 0) > 0 else "fail", "summary": f"bd_files={inspection.get('bd_files', '')}"})
        checks.append({"name": "app_shell_all_bd_opened", "status": "pass" if not bd_open_failures else "fail", "summary": f"failed_bd_count={len(bd_open_failures)}", "failures": bd_open_failures[:10]})
        checks.append({"name": "app_shell_board_axi_prefix_found", "status": "pass" if total_prefix_pins > 0 else "fail", "summary": f"prefix={signal_prefix} pins={inspection.get('total_prefix_pins', '0')}"})
        checks.append({
            "name": "app_shell_axi_candidate_discovery",
            "status": "pass" if total_intf_pins > 0 or cell_samples else "fail",
            "summary": f"intf_pins={total_intf_pins} axi_intf_pins={total_axi_intf_pins} cells_sampled={len(cell_samples)} candidate_cells={len(axi_candidate_cell_samples)}",
            "intf_pin_samples": intf_pin_samples[:20],
            "axi_intf_pin_samples": axi_intf_pin_samples[:20],
            "cell_samples": cell_samples[:20],
            "axi_candidate_cell_samples": axi_candidate_cell_samples[:20],
        })
        checks.append({"name": "app_shell_integration_target_declared", "status": "pass" if target_ip_name else "fail", "summary": f"target_ip_name={target_ip_name or '<missing>'}"})
        checks.append({"name": "app_shell_integration_ready", "status": "pass" if inspection.get("integration_ready") == "1" else "fail", "summary": inspection.get("integration_blocker", "")})
        check_summaries = {
            "app_shell_project_exists": f"project_xpr={project_xpr}",
            "app_shell_project_opened": inspection.get("open_project_message", ""),
            "app_shell_bd_present": f"bd_count={inspection.get('bd_count', '0')} bd_files={inspection.get('bd_files', '')}",
            "app_shell_all_bd_opened": f"failed_bd={bd_open_failures[:5]}",
            "app_shell_board_axi_prefix_found": (
                f"no BD pins/nets matched board_interface.signal_prefix={signal_prefix}; "
                f"discovered_intf_pins={intf_pin_samples[:10]} discovered_axi_intf_pins={axi_intf_pin_samples[:10]}"
            ),
            "app_shell_integration_target_declared": (
                "no integration target IP/block declared in app-shell contract or SPATIALACC_APP_SHELL_TARGET_IP; "
                f"target_discovery_status={target_discovery.get('status')} "
                f"selection_reason={target_discovery.get('selection_reason')} "
                f"cell_samples={cell_samples[:10]} candidate_cells={axi_candidate_cell_samples[:10]}"
            ),
            "app_shell_integration_ready": inspection.get("integration_blocker", ""),
        }
        for name, passed in [
            ("app_shell_project_exists", inspection.get("project_exists") == "1"),
            ("app_shell_project_opened", inspection.get("open_project_status") == "0"),
            ("app_shell_bd_present", int(inspection.get("bd_count", "0") or 0) > 0),
            ("app_shell_all_bd_opened", not bd_open_failures),
            ("app_shell_board_axi_prefix_found", total_prefix_pins > 0),
            ("app_shell_integration_target_declared", bool(target_ip_name)),
            ("app_shell_integration_ready", inspection.get("integration_ready") == "1"),
        ]:
            if not passed:
                blockers.append(f"{name} failed: {check_summaries.get(name, '')}")
    elif not blockers:
        blockers.append(f"app-shell Vivado inspection report missing: {inspection_path}")

    bit_candidates = sorted(out_dir.glob("*.bit"))
    if args.mode == "bitstream":
        checks.append({"name": "app_shell_runtime_bitstream_exists", "status": "pass" if bit_candidates else "fail", "paths": [str(path) for path in bit_candidates]})
        if not bit_candidates:
            blockers.append("no app-shell runtime bitstream artifact was produced")

    report = {
        "schema_version": "spatialaccagent.app_shell_runtime_vivado.v0",
        "status": "pass" if not blockers else "fail",
        "summary": "app-shell runtime Vivado flow passed" if not blockers else f"{len(list(dict.fromkeys(blockers)))} blocker(s)",
        "run_dir": str(run_dir),
        "mode": args.mode,
        "contract": str(args.contract),
        "wrapper_rtl": str(args.wrapper_rtl),
        "out_dir": str(out_dir),
        "tcl": str(tcl_path),
        "remote_host": remote_host,
        "remote_workdir": remote_workdir,
        "vivado_bin": vivado_bin,
        "shell_project_xpr": project_xpr,
        "signal_prefix": signal_prefix,
        "target_ip_name": target_ip_name,
        "target_discovery": {
            "status": target_discovery.get("status"),
            "selection_reason": target_discovery.get("selection_reason"),
            "candidate_count": target_discovery.get("candidate_count"),
            "selected_target": target_discovery.get("selected_target"),
            "top_candidates": target_discovery.get("candidates", [])[:8] if isinstance(target_discovery.get("candidates"), list) else [],
        },
        "inspection": inspection,
        "candidate_discovery": {
            "intf_pin_samples": split_report_list(inspection.get("intf_pin_samples", "")),
            "axi_intf_pin_samples": split_report_list(inspection.get("axi_intf_pin_samples", "")),
            "cell_samples": split_report_list(inspection.get("cell_samples", "")),
            "axi_candidate_cell_samples": split_report_list(inspection.get("axi_candidate_cell_samples", "")),
            "total_intf_pins": int(inspection.get("total_intf_pins", "0") or 0) if inspection else 0,
            "total_axi_intf_pins": int(inspection.get("total_axi_intf_pins", "0") or 0) if inspection else 0,
        },
        "checks": checks,
        "blockers": list(dict.fromkeys(blockers)),
        "commands": commands,
        "acceptance_policy": "Pass requires a real app-shell-integrated runtime bitstream, not standalone board-shell IO exposure.",
    }
    write_json(args.out, report)
    if report["status"] != "pass":
        print(report["summary"], file=sys.stderr)
        return 1
    print(report["summary"])
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
